### ISSUE TITLE
MicMac results in vignetting and holes (no data) in orthomosaic

### ISSUE THREAD

**Issue by NicholasK7** [OpenDroneMap/NodeMICMAC#25]
### How did you install WebODM? (Docker, natively, ...)?

Installed WebODM 0.9.1 in DockerToolbox $ ./webodm.sh update

### What's your browser and operating system? 

Chrome 75 on Windows 10

### What is the problem?

Output on MicMac node (default processing options) resulted in vignetting and minor yet noticeable holes orthmosaic aoi (see MicMac default with swipe over ODM custom [here](https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=cd4f98de-88ca-11e9-b9b8-0edaf8f81e27)) 

_Note: images may take a bit longer than usual to load in Juxtapose_ 

### What should be the expected behavior?

Ran default and custom options with ODM 0.9.0 (see comparison [here](https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=5cf73ea6-8623-11e9-b9b8-0edaf8f81e27)) without the vignetting, but ODM custom options did produce holes, although not apparently in aoi (ie uniform block of trees)...

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Original flight parameters, ODM custom options, and system specs [here](https://docs.google.com/spreadsheets/d/1O2fDOuwMSTD8Bo11_rXUQ-LzDiDMOfUYuajkV288Yss/edit?usp=sharing)

Unable to provide a copy of the image set...However, I am willing to run the images through Lightning Network and modify the options with any suggestions if there is a way to select MicMac processing.

**Comment by dronemapper-io** [comment]
Thanks for providing detailed information and screenshots. I think there are a few optimizations to the Ortho/Radiometric Balance process that may improve your situation. I'll do an update tomorrow and you can re-test/process.

**Comment by dronemapper-io** [comment]
MM and NodeMicMac updated, should improve results: https://github.com/dronemapper-io/NodeMICMAC/commit/fa7a53e32e7001a249b9050ebe1610e36013ddfa 
https://github.com/dronemapper-io/micmac/commit/c6923e6251e4f29599f500d997e2804d5764932e

**Comment by dronemapper-io** [comment]
closing for now, please attempt processing with latest docker and improved parameters. thanks

**Comment by NicholasK7** [comment]
Updated to WebODM 1.0.0 via command: $ ./webodm.sh update

after update was successful ran command $ ./webodm.sh restart --with-micmac

Then reprocessed same 697 images but till get same [results](https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=e3a34330-96bf-11e9-b9b8-0edaf8f81e27) as before. Is this sufficient to capture your changes?

Thank you

**Comment by pierotofy** [comment]
Nop, you should update with:

`./webodm.sh update --with-micmac`

**Comment by NicholasK7** [comment]
After update --with-micmac reprocessed same 697 images (with exif tags) now I get no Orthophoto or Point Cloud ??

![MicMac_Orthofail](https://user-images.githubusercontent.com/51466101/60306414-eac91680-98f4-11e9-9b2b-1303dda3a421.png)

(btw, when I try to download the console file it gives me a Failed - Network error)

DSM that was generated appears to have some differences from the previous process. The overall range in raster values (meters) went from 44.0235 - 27.1404 to 44.6808 - 26.5689, (16.8831‬ to 18.1119).

Q1: is there an indication in the processing that exif tags are not being correctly processed?
Q2: are dsm files generated from the same original photos going to vary from each processing?  

Thanks

**Comment by dronemapper-io** [comment]
Sorry for the problems. If you could share the options/parameters you used for processing that might help. Also, if you would like to share the log file privately -- we can evaluate. 

Q1 reply: The only indication is the failure of the processing after tie-point extraction and during the first bundle block stage
Q2 reply: Yes the DSM could differ but it shouldn't significantly change 

Something that might help would be to use the "multi-scale" tie-point options and set the initial image size to 800. It will take longer but produce more feature matches in homogenous terrain. 

If you could share the dataset privately, I could evaluate that as well.

**Comment by NicholasK7** [comment]
Options were default. Log file download from webodm fails. Do you have the path to the file in docker?

Before the last update I tried the 'multi-scale' option but it failed, seemed to overload already minimal memory resources.

Unfortunately I can not share the dataset.

**Comment by dronemapper-io** [comment]
No worries, understand. If the 'multi-scale' option fails due to server resources / memory that could be related to the issue. You can try the default settings but use the initial image size as 1000 or more pixels. I noticed it took 62 hrs to process which seems abnormally long.

**Comment by NicholasK7** [comment]
...It has always taken 60+ hours. However, the micmac orthomosaic qualities (minus the vignetting and no data holes) seemed to be better than the default of any other cloud based processing option...is there any system benchmarking data for processing times? 

Do you have an alternative path to the console (process log) file? Hoping that will provide insight into what is causing the problem.

**Comment by dronemapper-io** [comment]
I'm not sure if WebODM saves the console log somewhere. Maybe others can help identify that location if it exists?

**Comment by NicholasK7** [comment]
I'm currently reprocessing original 697 images running default options with nodeMicMac on a Google Cloud Platform instance (Machine type: n1-standard-8 (8 vCPUs, 30 GB memory; 100GB storage) in hopes it will isolate any local resource issues. 

![image](https://user-images.githubusercontent.com/51466101/60390085-4923ff80-9a83-11e9-97a9-576f821d05d5.png)

The inital console output is indicating the following: 

Error: Directory Iop: Next pointer is out of bounds; ignored.
Error: Directory (Last IFD item) with 65205 entries considered invalid; not read...

(error message is repeated with different numbers before the 'entries', eventually followed by a subset of the images like shown below, then more 'error:'...followed by the next subset of images)

DJI_0032.JPG : WGS84(rad) [-2.16316,0.828461,112.2] GeoC  [-2.41176e+06,-3.58365e+06,4.67713e+06]
DJI_0033.JPG : WGS84(rad) [-2.16316,0.828461,112.2] GeoC  [-2.41176e+06,-3.58365e+06,4.67712e+06]
DJI_0034.JPG : WGS84(rad) [-2.16316,0.82846,112.2] GeoC  [-2.41176e+06,-3.58365e+06,4.67712e+06]
DJI_0035.JPG : WGS84(rad) [-2.16316,0.828459,112.1] GeoC  [-2.41176e+06,-3.58366e+06,4.67712e+06]
DJI_0036.JPG : WGS84(rad) [-2.16316,0.828459,112.1] GeoC  [-2.41177e+06,-3.58366e+06,4.67711e+06]
DJI_0037.JPG : WGS84(rad) [-2.16316,0.828458,112.1] GeoC  [-2.41177e+06,-3.58366e+06,4.67711e+06]
DJI_0038.JPG : WGS84(rad) [-2.16316,0.828457,112.1] GeoC  [-2.41177e+06,-3.58367e+06,4.67711e+06]
DJI_0039.JPG : WGS84(rad) [-2.16316,0.828456,112.1] GeoC  [-2.41177e+06,-3.58367e+06,4.67711e+06]
DJI_0040.JPG : WGS84(rad) [-2.16316,0.828456,112.1] GeoC  [-2.41177e+06,-3.58367e+06,4.6771e+06]
DJI_0041.JPG : WGS84(rad) [-2.16316,0.828455,112.1] GeoC  [-2.41177e+06,-3.58367e+06,4.6771e+06]
DJI_0042.JPG : WGS84(rad) [-2.16316,0.828455,112.1] GeoC  [-2.41178e+06,-3.58368e+06,4.6771e+06]
DJI_0043.JPG : WGS84(rad) [-2.16316,0.828454,112.1] GeoC  [-2.41178e+06,-3.58368e+06,4.67709e+06]
DJI_0044.JPG : WGS84(rad) [-2.16316,0.828453,112.2] GeoC  [-2.41178e+06,-3.58368e+06,4.67709e+06]
DJI_0045.JPG : WGS84(rad) [-2.16316,0.828452,112.2] GeoC  [-2.41178e+06,-3.58369e+06,4.67709e+06]
DJI_0046.JPG : WGS84(rad) [-2.16316,0.828452,112.2] GeoC  [-2.41178e+06,-3.58369e+06,4.67708e+06]
DJI_0047.JPG : WGS84(rad) [-2.16316,0.828451,112.2] GeoC  [-2.41178e+06,-3.58369e+06,4.67708e+06]
DJI_0048.JPG : WGS84(rad) [-2.16316,0.82845,112.2] GeoC  [-2.41179e+06,-3.58369e+06,4.67708e+06]
DJI_0049.JPG : WGS84(rad) [-2.16316,0.82845,112.2] GeoC  [-2.41179e+06,-3.5837e+06,4.67708e+06]
DJI_0050.JPG : WGS84(rad) [-2.16316,0.828449,112.2] GeoC  [-2.41179e+06,-3.5837e+06,4.67707e+06]
DJI_0051.JPG : WGS84(rad) [-2.16316,0.828448,112.2] GeoC  [-2.41179e+06,-3.5837e+06,4.67707e+06]
DJI_0052.JPG : WGS84(rad) [-2.16316,0.828447,112.2] GeoC  [-2.41179e+06,-3.58371e+06,4.67707e+06]
DJI_0053.JPG : WGS84(rad) [-2.16316,0.828447,112.2] GeoC  [-2.41179e+06,-3.58371e+06,4.67706e+06]
DJI_0054.JPG : WGS84(rad) [-2.16316,0.828446,112.2] GeoC  [-2.4118e+06,-3.58371e+06,4.67706e+06]
DJI_0055.JPG : WGS84(rad) [-2.16316,0.828445,112.2] GeoC  [-2.4118e+06,-3.58371e+06,4.67706e+06]
DJI_0056.JPG : WGS84(rad) [-2.16316,0.828445,112.2] GeoC  [-2.4118e+06,-3.58372e+06,4.67705e+06]
DJI_0057.JPG : WGS84(rad) [-2.16316,0.828444,112.2] GeoC  [-2.4118e+06,-3.58372e+06,4.67705e+06]
DJI_0058.JPG : WGS84(rad) [-2.16316,0.828443,112.2] GeoC  [-2.4118e+06,-3.58372e+06,4.67705e+06]
DJI_0059.JPG : WGS84(rad) [-2.16316,0.828443,112.2] GeoC  [-2.41181e+06,-3.58372e+06,4.67705e+06]
DJI_0060.JPG : WGS84(rad) [-2.16316,0.828442,112.2] GeoC  [-2.41181e+06,-3.58373e+06,4.67704e+06]
DJI_0061.JPG : WGS84(rad) [-2.16316,0.828441,112.2] GeoC  [-2.41181e+06,-3.58373e+06,4.67704e+06]
DJI_0062.JPG : WGS84(rad) [-2.16316,0.82844,112.2] GeoC  [-2.41181e+06,-3.58373e+06,4.67704e+06]
DJI_0063.JPG : WGS84(rad) [-2.16316,0.82844,112.2] GeoC  [-2.41181e+06,-3.58374e+06,4.67703e+06]
DJI_0066.JPG : WGS84(rad) [-2.16316,0.82844,112.2] GeoC  [-2.41181e+06,-3.58374e+06,4.67704e+06]
DJI_0067.JPG : WGS84(rad) [-2.16316,0.828441,112.2] GeoC  [-2.4118e+06,-3.58373e+06,4.67704e+06]
DJI_0068.JPG : WGS84(rad) [-2.16316,0.828442,112.2] GeoC  [-2.4118e+06,-3.58373e+06,4.67704e+06]
DJI_0069.JPG : WGS84(rad) [-2.16316,0.828443,112.2] GeoC  [-2.4118e+06,-3.58373e+06,4.67705e+06]
DJI_0070.JPG : WGS84(rad) [-2.16316,0.828443,112.2] GeoC  [-2.4118e+06,-3.58373e+06,4.67705e+06]
DJI_0071.JPG : WGS84(rad) [-2.16316,0.828444,112.2] GeoC  [-2.4118e+06,-3.58372e+06,4.67705e+06]
DJI_0072.JPG : WGS84(rad) [-2.16316,0.828445,112.2] GeoC  [-2.41179e+06,-3.58372e+06,4.67705e+06]
DJI_0073.JPG : WGS84(rad) [-2.16316,0.828445,112.2] GeoC  [-2.41179e+06,-3.58372e+06,4.67706e+06]
DJI_0074.JPG : WGS84(rad) [-2.16316,0.828446,112.2] GeoC  [-2.41179e+06,-3.58371e+06,4.67706e+06]
DJI_0075.JPG : WGS84(rad) [-2.16316,0.828447,112.2] GeoC  [-2.41179e+06,-3.58371e+06,4.67706e+06]
DJ
Error: Directory Iop: Next pointer is out of bounds; ignored.
Error: Directory (Last IFD item) with 10027 entries considered invalid; not read.

Not sure if this error was present when I first ran MicMac and was able to generate an orthophoto on the same dataset, but so far this is the only indication something is not processing correctly...

If the GCP instance finishes this and the problem generating an ortho persists may I send you the complete console file?

**Comment by NicholasK7** [comment]
MicMac failed to generate an Orthophoto & LAS on the dataset it had previously been successful with. The failure was the same on a Google Cloud instance so I can't see it being a local resource issue...

![image](https://user-images.githubusercontent.com/51466101/60395344-dd737e00-9ae6-11e9-9b3f-1e6fd2e38a8e.png)
 
...although it only took 13 hrs on Google Cloud vs 60+ on my laptop.

Complete console output file [here](https://drive.google.com/open?id=18mmwcUcXzaBS7lqviRVMzR2y4Exf3ZIG)

**Comment by dronemapper-io** [comment]
Thanks for the log. That helps! I believe the problem might be a recently introduced option to Tawny `DEq=1` ... I will reverse that and push a new release. It might help. 

```
[DEBUG]   running mm3d Tawny Ortho-MEC-Malt DEq=1 RadiomEgal=1 DegRapXY=4 SzV=25
------------------------------------------------------------
|   Sorry, the following FATAL ERROR happened
|
|    REadPt
|
------------------------------------------------------------
-------------------------------------------------------------
|       (Elise's)  LOCATION :
|
| Error was detected
|          at line : 1169
|          of file : /var/www/micmac/src/util/pt2di.cpp
-------------------------------------------------------------
Bye  (press enter)
[ERROR]   Child returned 1
[DEBUG]   running mm3d Nuage2Ply MEC-Malt/NuageImProf_STD-MALT_Etape_9.xml Attr=Ortho-MEC-Malt/Orthophotomosaic.tif 64B=1 Out=/var/www/data/73277a88-0d38-4a6a-8148-5553eeeb62a6/odm_georeferencing/odm_georeferenced_model.ply
ERROR: colour image [Ortho-MEC-Malt/Orthophotomosaic.tif] does not exist
[ERROR]   Child returned 1
```

**Comment by dronemapper-io** [comment]
I've made some updates to the ortho creation/color balance. https://github.com/dronemapper-io/NodeMICMAC/commit/4070a6eb28b13a9bd35588f6fb92934322b2370c

I would wait for docker hub to finish building the new image and give it a try. Thanks

**Comment by kikislater** [comment]
@dronemapper-io strange for DEq=1!

**Comment by dronemapper-io** [comment]
@kikislater no worries, probably other Tawny commands / options as well. I switched it over to Porto with a custom config xml that we've been using at DroneMapper. Should work better for many cases.... fingers crossed
https://github.com/dronemapper-io/micmac/commit/1646049bbd0cb5abf12ff663fe93a65c56fa37cb

**Comment by NicholasK7** [comment]
Attempt 2 on GCP with MicMac failed to generate an Orthophoto and render PLY...

![DF_Progeny_MicMac_GCP](https://user-images.githubusercontent.com/51466101/60457123-1ea38500-9bf0-11e9-9ede-05c8fe4cee55.png)

...I was able to download a .ply file individually that was in the MB range of previous MicMac processing, but no luck with the orthophoto

Console output [here](https://drive.google.com/file/d/19K7HRi2ueM5UU7YnJKA08JsYx24U_hyh/view?usp=sharing)

**Comment by dronemapper-io** [comment]
I've reverted one other MicMac commit -- you can test it once the docker image is done building. https://github.com/dronemapper-io/micmac/commit/b9475765c20f8297630f4a4f3319451dfe08bba4

I would also recommend testing your entire process with the DroneMapper 4th Ave. example data set as well. Thanks

**Comment by NicholasK7** [comment]
After starting a new instance on Google Cloud and running latest updates yesterday the issues with no ortho/PLY outputs on the 697 image set persisted, same output as noted July 1 (screenshots [here](https://drive.google.com/file/d/1cRRJwB6AGu897_23jD_sCr7BvEe9FM_5/view?usp=sharing)) 

However I did run a different 263 image set, over varying forest conditions, on the new instance Google Cloud and was able to get all the outputs...though there are some ortho and dsm discrepancies. The ortho/dsm comparison between nodeODM and nodeMicMac is [here ](https://refor.maps.arcgis.com/apps/View/index.html?appid=b8c18654c6984fb7b538985ff8f7269b)

Btw, is there a way to get a '.las' file instead of the '.ply' in the MicMac output? ...finding .ply file more limiting in the applications I use. 

...I will try the 4th Ave data set shortly

**Comment by NicholasK7** [comment]
***Update***
Still no luck with the 697 image dataset...latest console output [txt file](https://drive.google.com/file/d/1J3sB4WEI7kDzmKyprCQP31gVIXYdMgZY/view?usp=sharing) and WebODM screenshots [here
](https://drive.google.com/file/d/17t0tPFRy-J9h5nex_T7UaqpRiZg0mD7m/view?usp=sharing)

Any thoughts on why the ortho is not rendering?

Just fyi, after analyzing the 4th Ave ortho and dsm my processing varied considerably, particularly for the trees...GCP instance is 8vCPUs x 30GB memory x 150GB storage: [monitoring graphs](https://drive.google.com/open?id=1QGs6qOLfm3a1KRwkovismlkaeF-OPSl1)
Results [.zip](https://drive.google.com/open?id=1ylBsmU0FNxPH0kQnFwP62L0Tnfi8p2iW)
Console output [txt file](https://drive.google.com/open?id=1lOP6Q0krpjCgqHb0vMqqzZ7J7W2QlwMs)

**Comment by dronemapper-io** [comment]
I'll take a look.. but unfortunately, I can't really diagnose and fix the issue or determine the issue without the data/imagery. Thanks

**Comment by NicholasK7** [comment]
Let me know if you get this message and I can send a gdrive link to the 697
image set I have been having trouble with in nodeMicMac.

Also wondering if I could upload the data through DroneMapper and if you
offer a pay as you go service similar to Lightning?

Thank you for any help on this.

-Nick

**Comment by dronemapper-io** [comment]
We can definitely take a look and try the processing locally with nodeMicMac.. please send a contact via https://dronemapper.com

**Comment by dronemapper-io** [comment]
I wasn't able to fix the bug yet. But for this data set a potential workaround is to remove every other image and run the processing. I got a well balanced Ortho, DEM and Point Cloud. I shared the results privately to you. Thanks

![image](https://user-images.githubusercontent.com/47226666/62501436-25ea1f80-b7a8-11e9-8b6b-5231a13051a3.png)

**Comment by kikislater** [comment]
Closed due to inactivity
