### ISSUE TITLE
Processing instantly fails with error: Could not start process (spawn /code/run.sh ENOENT)

### ISSUE THREAD

**Issue by andreas-eberle** [OpenDroneMap/NodeMICMAC#36]
Hi guys,

I'm trying to test NodeMICMAC with the [DroneMapper 4thAve Reservoir dataset](https://dronemapper.com/sample_data/). 

I build the NodeMICMAC docker container as described in the readme and started it on my Windows 10 computer. On the localhost web ui, I selected the images of the dataset and hit the "start task" button. As soon as all images are uploaded into the container, the task is displayed as "failed". The task details show the following:

```
uuid | "a98db4c0-75c1-44b7-a57c-7655d61a1d66"
name | "Task of 2019-09-26T06:58:09.580Z"
dateCreated | 1569481089580
processingTime | 7
status |  
code | 30
errorMessage | "Could not start process (spawn /code/run.sh ENOENT)"
options | []
imagesCount | 48
progress | 100
```

The docker container does only display the following:
```
info: Authentication using NoTokenRequired
info: Listening on 0.0.0.0:6367 UDP for progress updates
info: No tasks dump found
info: Checking for orphaned directories to be removed...
info: Server has started on port 3000
info: About to run: /code/run.sh --project-path /var/www/data 61e01749-811b-4888-af46-26775f8466d6
```

Do you have an idea, what I'm doing wrong? Thanks for your help!

Edit: The same images work with NodeODM.

**Comment by dronemapper-io** [comment]
We'll take a look asap. Thanks

**Comment by spgriffin** [comment]
I am also having this same issue, Windows 10 machine.  I typically use nodeODM without issue, but built nodeMicMac from Dockerfile to try.  I even tried removing all repositories and images to start from scratch, but the issue persists.

{"uuid":"ff35dbb5-094e-42ac-9980-8be7ee06dd73","name":"Test","dateCreated":1599206322004,"processingTime":9,"status":{"code":30,"errorMessage":"Could not start process (spawn /code/run.sh ENOENT)"},"options":[],"imagesCount":187,"progress":100}

I have searched various posts with the same issue, but yet to find a solid solution.  Appreciate any suggestions.

**Comment by kikislater** [comment]
Reopen if still an issue
