### ISSUE TITLE
Only one CPU is used

### ISSUE THREAD

**Issue by u5000** [OpenDroneMap/NodeMICMAC#40]
Hello and thank you for all your work.

I have a machine with 32 CPUs (each 1 core) and i can't figure out how to make NodeMICMAC to use more than one CPU. Is there a special command for that? I found the parameter to tell it how many cores it should use, but now how many CPUs.

I use docker+webodm+nodemicmac

thank you again.

**Comment by dronemapper-io** [comment]
Hello:
You should use this parameter:
```
  --max-concurrency <integer>
                        The maximum number of cores to use in processing.
                        Default: 4
```
Certain processes in the pipeline are single threaded won't use more than 1 thread/CPU. For example, the alignment / calibration step and the orthomosaic creation step. Thanks

**Comment by u5000** [comment]
yea was doing this (with number 32).
But only ever one CPU was used (looked at the CPU rate very often).

One project took about 20 hours. Where with the normal webodm node it would only take 1-2 hours.

Im using a virtual server with 32 CPUs for clarification.

**Comment by dronemapper-io** [comment]
Can you post the parameters you are using?

**Comment by u5000** [comment]
I did several tests:

**Using the webgui of WebODM:**
- ccd-width: 13.2, max-concurrency: 32, multi-scale: true, ccd-height: 8.8, image-footprint: true, camera-cloud: true

- ccd-width: 13.2, max-concurrency: 32, matcher-distance: 50, ccd-height: 8.8

- Default settings (at least 4 CPUs should have been used here)

**Using the webgui of nodemicmac directly:**

- ccd-width: 13.2, max-concurrency: 32, multi-scale: true, ccd-height: 8.8, image-footprint: true, camera-cloud: true

All of those attempts never raised the CPU usage above one CPU.

As i said, my setup has 32 CPUs, which are utilized by the odm_node but not on micmac.

**Comment by dronemapper-io** [comment]
Thanks for the details. We using NodeMICMAC what are you resizing the
images to? Can you share (privately if you want) a few example images and
log export? If you watch via terminal using the 'top' command, the feature
extraction and DEM construction should be multi-threaded. Thanks

**Comment by u5000** [comment]
Sorry for the late response. Yea i did watched the top command.
I just updated everything again and it might be faster now, i need a few days to observe. Anyway i think there is a lot of potential for further parallelisation, since nodeodm is a lot faster (and uses more CPU time) in comparison.

**Comment by dronemapper-io** [comment]
Thanks. Keep us posted. Sure, there are improvements that can be made. I
would suggest looking into making Porto multi-threaded and/or making Apero
multi-threaded -- no small task! Submit a PR and contributions are always
welcome.

**Comment by kikislater** [comment]
Latest version of micmac is now in this repository, I closed this one
