### ISSUE TITLE
ERROR 6: zoom_level > 22 not supported

### ISSUE THREAD

**Issue by rumenmitrev** [OpenDroneMap/NodeMICMAC#42]
Hello,

I have manged to compile micmac natively  on Ubuntu 16.04.
And use it via NodeMicmac and WebODM.
Initially it failed at orthophoto step. I asked in [micmac forum](http://forum-micmac.forumprod.com/micmac-quot-cannot-handle-substitution-quot-t1887.html) and they suggest to replace 
this command in run.py

`#system.run('{mm3d} Porto Ortho-MEC-Malt/Param-Tawny.xml'.format(**kwargs_malt))`

whit this:

`#system.run('{mm3d} Tawny Ortho-MEC-Malt'.format(**kwargs_malt))
`

Now orthophoto and surface models are excellent.

But it fails at point cloud step with:

```
ERROR 6: zoom_level > 22 not supported

Point cloud tiles will not be generated

Postprocessing: done (•̀ᴗ•́)و!

Compressing all.zip

Done!
```

Actually there is point cloud and if I downloaded, I can open it in Meshlab
But cant be seen in WebODM , and it fails with:
"Could not load point cloud. This task doesn't seem to have one. Try processing the task again."

bin/mm3d CheckDependencies

```
Code:
git revision : v1.0.beta13-612-ga2c0eb1

byte order   : little-endian
address size : 64 bits

micmac directory : [/home/drnmppr-micmac/]
auxilary tools directory : [/home/drnmppr-micmac/binaire-aux/linux/]

make:  found (/usr/bin/make)
exiftool:  found (/usr/bin/exiftool)
exiv2:  found (/usr/bin/exiv2)
convert:  found (/usr/bin/convert)
proj:  found (/usr/bin/proj)
cs2cs:  found (/usr/bin/cs2cs)
```
[complete console output
](https://drive.google.com/file/d/1kV3NIbn920LXks4lr6jIK1T5HWLeEs4x/view?usp=sharing)

EDIT1:
Actually using docker image `docker run -d -p 3001:3000 dronemapper/node-micmac` produce the same result. "ERROR 6: zoom_level > 22 not supported" and no point cloud in WebODM

**Comment by dronemapper-io** [comment]
It appears that this is an error with MBTILES. You may want to constrain the mbtile creation to a MIN/MAX zoom level: https://gdal.org/drivers/raster/mbtiles.html

```
MINZOOM=integer: Minimum zoom level at which tiles are generated. Defaults to 0.

MAXZOOM=integer: Minimum zoom level at which tiles are generated. Defaults to 5. Maximum supported value is 22
```

**Comment by rumenmitrev** [comment]
Excuse me for my ignorance , but can you point me how to rectify this.
Thank you in advance.

**Comment by dronemapper-io** [comment]
It is hard to point you to the exact location or solve the issue as I haven't been able to reproduce. If you want to share the resulting processed products we can take a look. It looks like some params need modification: 
https://github.com/dronemapper-io/NodeMICMAC/blob/bdc0b263be1b0593d06c189a6cea015e4e67042d/scripts/postprocess.sh#L39

or here: https://github.com/dronemapper-io/NodeMICMAC/blob/bdc0b263be1b0593d06c189a6cea015e4e67042d/scripts/postprocess.sh#L58

i'll try and run the example data and see if the error shows up

**Comment by dronemapper-io** [comment]
I just ran the 4th Ave example with a fresh docker image pull with no issues. Tiles for DSM/Ortho were generated. If you'd like to share your data we can try to take a look

**Comment by rumenmitrev** [comment]
[dataset](https://community.opendronemap.org/t/sheffield-park-1/58)
[console output](https://drive.google.com/open?id=1SzxDOSHsIop9R1nUOv1b0zOz09KaWPNc)
[all.zip](https://drive.google.com/open?id=1hL0GN3PeaN65wbVH4qltSeHqKvB-DZ7E)

**Comment by dronemapper-io** [comment]
I replicated the error with the ODM data set. I'll dig into it when time permits

**Comment by dronemapper-io** [comment]
You can replicate the error inside the docker container like this:
```
root@41b0f421f1a1:/var/www/data/3b76a2f8-2a95-4a84-a316-fe7156d73fd4# gdal_translate odm_orthophoto/odm_orthophoto.tif odm_orthophoto/odm_orthophoto.mbtiles -of MBTILES
Input file size is 10612, 7608
ERROR 6: zoom_level > 22 not supported
0...10...20...30...40...50...60...70...80...90...100 - done.
```

I was able to get the tiles properly generated using:
```
root@41b0f421f1a1:/var/www/data/3b76a2f8-2a95-4a84-a316-fe7156d73fd4# gdal_translate odm_orthophoto/odm_orthophoto.tif odm_orthophoto/odm_orthophoto.mbtiles -of MBTILES -co "ZOOM_LEVEL_STRATEGY=LOWER"
Input file size is 10612, 7608
0...10...20...30...40...50...60...70...80...90...100 - done.
```

not sure the implications to WedODM if this command is changed, will look into it. I wasn't able to replicate this issue on our 4th Ave example data and haven't seen it before with other datasets

**Comment by kikislater** [comment]
Reopen if still an issue
