### ISSUE TITLE
Adapt NodeMicMac for python3

### ISSUE THREAD

**Issue by rumenmitrev** [OpenDroneMap/NodeMICMAC#50]
Is it possible?
What needs to be done?

**Comment by kikislater** [comment]
Good idea, i think it's not difficult and almost done in NodeODM. 
This PR : https://github.com/OpenDroneMap/NodeODM/pull/124/ check what to change and more. 
@pierotofy Could we move forward to this : applying NodeODM PR in NodeMicmac?

**Comment by pierotofy** [comment]
Yeah it should be possible; there might be a few conflicts to resolve, but should be doable.

I'd welcome a pull request!

**Comment by kikislater** [comment]
I got it ... Just some small modifications but build and running with 20.04 is ok. 
I will submit PR soon

**Comment by kikislater** [comment]
I have updated to Ubuntu 20.04, Python 3 on this branch and some tweaks on non working parts like geojson footprint, standardization to NodeODM project ... 

More to come ! But before, need to move to new ODM code and license ... 

https://github.com/kikislater/NodeMICMAC/tree/python3
https://github.com/kikislater/NodeMICMAC/commit/f1c7d03773f48d22370853da3ed44d96b87b3bcb

**Comment by kikislater** [comment]
Done ! https://github.com/OpenDroneMap/NodeMICMAC/pull/54
