### ISSUE TITLE
View 3D model does not show anything

### ISSUE THREAD

**Issue by sbonaime** [OpenDroneMap/NodeMICMAC#52]
Hi,

I successfully process 125 images through OpenDroneMap and the NodeMICMAC with the following parameters
Options: ccd-width: 7.4, multi-scale: true, ccd-height: 5.55

I can see the orthophoto and the Surface model. but When I click the "View 3D model", I can see nothing.  Do I have to do something to see the 3D model ? Do you need the logs ? 

Is there a way to filter the side effects (see picture) on the Surface Model ? 
![Capture d’écran 2020-12-17 à 17-12-20 11 43 07](https://user-images.githubusercontent.com/750709/102477757-10079280-405d-11eb-8e26-7aa7cd7fc0f0.png)

Thank you

**Comment by kikislater** [comment]
If recent WebODM, it needs adaptation as WebODM changed and it needs to be adapted to the new version. WebODM move from Potree to Entwine and now Untwine whereas NodeMicMac still use Potree

But to go forward at this time :
- You could crop your dem with gdal (tools available in qgis : raster menu > extract )
- View point cloud in other tool such as Meshlab or CloudCompare : both opensource

**Comment by sbonaime** [comment]
I use the latest WebODM.

Thank you

**Comment by kikislater** [comment]
So you need to wait update ...
