### ISSUE TITLE
Entwine crash

### ISSUE THREAD

**Issue by kikislater** [OpenDroneMap/NodeMICMAC#65]
### What is the problem?

Entwine crash during .ply conversion

### What should be the expected behavior?

.ply generation without error

### How can we reproduce this? (What steps did you do to trigger the problem? Be detailed)

Launch a process with NodeMicMac, this will give following error :

```
terminate called after throwing an instance of 'nlohmann::detail::out_of_range'
  what():  
[json.exception.out_of_range.403] key 'bounds' not found

/var/www/scripts/postprocess.sh: line 126: 11063 Aborted                 (core dumped) entwine build --threads $(nproc) --tmp "entwine_pointcloud-tmp" -i "$pointcloud_input_path" -o entwine_pointcloud

Postprocessing: done (•̀ᴗ•́)و!

Compressing all.zip

Done!
```

**Comment by kikislater** [comment]
@rumenmitrev Any idea ?

**Comment by rumenmitrev** [comment]
Is it happening with different dataset?
