### ISSUE TITLE
Build instructions are incorrect

### ISSUE THREAD

**Issue by Maxli-Cat** [OpenDroneMap/NodeMICMAC#68]
The main github page currently instructs people to use the docker image `odm/node-micmac`, which is incorrect, and should be `opendronemap/nodemicmac`

**Comment by kikislater** [comment]
Done 
https://github.com/OpenDroneMap/NodeMICMAC/commit/8c7b667f49f985ab34ecbd6a05c335573da9748e
https://github.com/OpenDroneMap/NodeMICMAC/commit/8c7b667f49f985ab34ecbd6a05c335573da9748e
