### ISSUE TITLE
How to contribute ? 

### ISSUE THREAD

**Issue by sbonaime** [OpenDroneMap/NodeMICMAC#70]
Hi,

I would be interested to contribute to NodeMICMAC. But right now, I don't understand how MicMac is embeded in NodeMICMAC ! 
Maybe we can start a dev documentation to explain how things work and maybe it will attract new people. 

From README, the latest NodeMICMAC is based on  Mimac Cloned: 2022-06-05 Commit: 797e98d . 
Latest Micmac version is from Mar 30, 2023. So maybe we can upgrade Mimac ? 

Is there any way (Slack, Telegram ... ) to talk with people working on Nodeodm ? 
Thanks

**Comment by kikislater** [comment]
It's emebed like others opendronemap project:
- core code like ODM : micmac from this repository => https://github.com/OpenDroneMap/micmac/
- simple node repo here to provide API and web interface with nodejs. It calls micmac with python code

Feel free to contribute, I have upgraded micmac repo from last PR of @rumenmitrev which was syncing his micmac repo from IGN upstream. Micmac was modified by dronemapper to work with nodejs and enhance some worflows / settings.
You can drop me a message if you want to discuss in french.
