### ISSUE TITLE
Ground Control Points (GCP) problem

### ISSUE THREAD

**Issue by sbonaime** [OpenDroneMap/NodeMICMAC#71]
I have the following problem using a gcp_list.txt file : 
````
 An orthophoto could not be generated. To generate one, make sure GPS information is embedded in the EXIF tags of your images, or use a Ground Control Points (GCP) file.
````
and in the log
````
[INFO]    Converting GCP.
[ERROR]   'str' object has no attribute 'decode'
Postprocessing: /var/www/data/7704bff8-af46-4de2-996b-16993ad861b0
No orthophoto found at odm_orthophoto/odm_orthophoto.tif: will skip tiling
````
without the gcp_list.txt and the same files I can get an orthophoto. 

I tried to use those two flavors of EPGS  wihout succes 
````
+proj=longlat +datum=WGS84 +no_defs +type=crs
45.287895853788044 -12.80125900948696 -17.178983656311 3122.2711714540274 1876.5399521009977 100_0001_0232.JPG
45.287895853788044 -12.80125900948696 -17.178983656311 3364.465801792682 1716.4372604837804 100_0007_0012.JPG
45.287895853788044 -12.80125900948696 -17.178983656311 3177.15777161748 1159.3214057940663 100_0001_0231.JPG
45.287895853788044 -12.80125900948696 -17.178983656311 3049.7143541681817 2577.3550061562523 100_0001_0233.JPG
45.287895853788044 -12.80125900948696 -17.178983656311 3350.9556621346846 2411.1540028558943 100_0007_0013.JPG
45.28774235547903 -12.801396452907344 -17.3792802490234 3024.515606625788 1636.320572646652 100_0007_0011.JPG
````
And
````
EPSG:4326
45.287895853788044 -12.80125900948696 -17.178983656311 3122.2711714540274 1876.5399521009977 100_0001_0232.JPG
45.287895853788044 -12.80125900948696 -17.178983656311 3364.465801792682 1716.4372604837804 100_0007_0012.JPG
45.287895853788044 -12.80125900948696 -17.178983656311 3177.15777161748 1159.3214057940663 100_0001_0231.JPG
45.287895853788044 -12.80125900948696 -17.178983656311 3049.7143541681817 2577.3550061562523 100_0001_0233.JPG
45.287895853788044 -12.80125900948696 -17.178983656311 3350.9556621346846 2411.1540028558943 100_0007_0013.JPG
45.28774235547903 -12.801396452907344 -17.3792802490234 3024.515606625788 1636.320572646652 100_0007_0011.JPG
````

In the readme we can read :
````
You can substitute the 2 GCP files above for a single GCP file that matches ODM format and is named gcp_list.txt. Below is an example of ODM format:
+proj=utm +zone=12 +ellps=WGS84 +datum=WGS84 +units=m +no_defs 
575133.061 4776173.433 340.348 1975 1313 DJI_0012.JPG
575133.061 4776173.433 340.348 1957 2246 DJI_0013.JPG
575133.061 4776173.433 340.348 2047 1151 DJI_0017.JPG
````
With ODM I can user EPSG:4326 as a header without problem. 
Maybe I need to convert GCP coordinates to a local projection enven if in ODM documentation it is not needed 
````
The first line should contain the name of the projection used for the geo coordinates. This can be specified either as a PROJ string (e.g. +proj=utm +zone=10 +ellps=WGS84 +datum=WGS84 +units=m +no_defs), EPSG code (e.g. EPSG:4326) or as a WGS84 UTM <zone>[N|S] value (eg. WGS84 UTM 16N)
````
If the conversion is mandatory for MicMac, maybe we can add a step in  the process in case we find EPSG:4326 in the header of the gcp file. There are some tools [(proj)](https://foresttechnology.blog/2022/02/06/transforming-geospatial-coordinates-from-the-command-line/) to convert from EPSG:4326 to any projections. But we will need an output EPSG from the parameters

**Comment by sbonaime** [comment]
same results after converting GCP coordinates to a local projection (EPSG:4471)
````
+proj=utm +zone=38 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +type=crs
531244.59 8584824.74 -17.178983656311 3122.2711714540274 1876.5399521009977 100_0001_0232.JPG
531244.59 8584824.74 -17.178983656311 3364.465801792682 1716.4372604837804 100_0007_0012.JPG
531244.59 8584824.74 -17.178983656311 3177.15777161748 1159.3214057940663 100_0001_0231.JPG
531244.59 8584824.74 -17.178983656311 3049.7143541681817 2577.3550061562523 100_0001_0233.JPG
````

**Comment by kikislater** [comment]
Yes some work is needed with GCP file... as it only supports UTM and it should be aligned to NodeODM. Not a big work, but it is needed to be done.
You can get inspiration with two separated files from the _DroneMapper Greg 1 & 2 Reservoir - 189 Geo-Tagged Images DJI Phantom 3 Advanced w/ Trimble 5800 Surveyed GCP Dat_a on the readme page.
 
**GCP_2D.txt** is coordinates in pixel in image like:
>MicMac GCP 2D - target locations in images
>GCPNAME IMAGE PIXELX PIXELY
Example:
```
1 DJI_0065.JPG 3036 1244
1 DJI_0066.JPG 3022 1915
```


**GCP_3D.txt** is measured gcp with gnss
> MicMac GCP 3D - real world target position on ground (UTM)
> GCPNAME UTMX UTMY Z PRECISIONXY PRECISIONZ
Example:
```
base 250021.111 4319269.236 2593.462 0.005 0.005
1 250002.422 4319308.241 2594.213 0.005 0.005
```

Comment in code about GCP: 
```
    Convert MicMac GCP TXT files to MicMac GCP XML format
    :param image_dir: path
    :return:

    Expects files to be named, GCP_2D.txt and GCP_3D.txt or ODM format: gcp_list.txt

    GCP_2D.txt format (single space delimiter):
    GCP IMAGENAME PIXELX PIXELY

    GCP_3D.txt format (single space delimiter):
    GCP UTMX UTMY Z PRECISION X/Y PRECISIONZ
```

Source : https://github.com/OpenDroneMap/NodeMICMAC/blob/master/dm/run.py#L160-L258

Worth reading => https://github.com/OpenDroneMap/NodeMICMAC/issues/21#issuecomment-496016660

For single file, I think I never tried but it should work with UTM regarding this commit : https://github.com/OpenDroneMap/NodeMICMAC/commit/cd5abcc2c3c83b778162a1e0ff3b3a4a94d0499a from this PR https://github.com/OpenDroneMap/NodeMICMAC/pull/37

**Comment by sbonaime** [comment]
https://github.com/OpenDroneMap/NodeMICMAC/pull/72

**Comment by kikislater** [comment]
> ok. I found maybe a problem. I don't understand why the gcp_list.txt is read like that
> 
> ```
>                 contents = f.read().decode('utf-8-sig').encode('utf-8').strip()
> ```
> 
> It is supposed to be an ascii txt file. Time for my first commit !

Because it was like that in ODM code =>Check this PR https://github.com/OpenDroneMap/ODM/commit/443560f047e97ea55935f19babc43ad53df847ea#diff-d8553354840bdd09e5ed13f55c76d996fd247b864fb650add40674aedbe2b939

**Comment by kikislater** [comment]
Reopen : Malformed GCP line
